--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./xls/i18n.xlsx

local GlobalTextXls = {
    Day = {
        Key = 'Day',
        _Text = 'Global_Text_Day'
    },
    Hour = {
        Key = 'Hour',
        _Text = 'Global_Text_Hour'
    },
    Minute = {
        Key = 'Minute',
        _Text = 'Global_Text_Minute'
    },
    Second = {
        Key = 'Second',
        _Text = 'Global_Text_Second'
    },
    Expired = {
        Key = 'Expired',
        _Text = 'Global_Text_Expired'
    },
    Source = {
        Key = 'Source',
        _Text = 'Global_Text_Source'
    }
}

return GlobalTextXls
