--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./xls/i18n.xlsx

local I18NXls = {
    SubType_Label_All = {
        Key = 'SubType_Label_All',
        zh_CN = '全部',
        en = 'All',
        id = 'Semua'
    },
    SubType_Label_Short = {
        Key = 'SubType_Label_Short',
        zh_CN = '短发',
        en = 'Short',
        id = 'Pendek'
    },
    SubType_Label_Medium = {
        Key = 'SubType_Label_Medium',
        zh_CN = '中长发',
        en = 'Medium',
        id = 'Medium'
    },
    SubType_Label_Long = {
        Key = 'SubType_Label_Long',
        zh_CN = '长发',
        en = 'Long',
        id = 'Panjang'
    },
    SubType_Label_Braids = {
        Key = 'SubType_Label_Braids',
        zh_CN = '辫子',
        en = 'Braids',
        id = 'Kepang'
    },
    SubType_Label_Special = {
        Key = 'SubType_Label_Special',
        zh_CN = '特殊',
        en = 'Special',
        id = 'Spesial'
    },
    SubType_Label_Accessories = {
        Key = 'SubType_Label_Accessories',
        zh_CN = '配饰',
        en = 'Accessories',
        id = 'Aksesori'
    },
    SubType_Label_Hats = {
        Key = 'SubType_Label_Hats',
        zh_CN = '帽子',
        en = 'Hats',
        id = 'Topi'
    },
    SubType_Label_Fun = {
        Key = 'SubType_Label_Fun',
        zh_CN = '趣味',
        en = 'Fun',
        id = 'Seru'
    },
    SubType_Label_Glasses = {
        Key = 'SubType_Label_Glasses',
        zh_CN = '眼镜',
        en = 'Glasses',
        id = 'Kacamata'
    },
    SubType_Label_Others = {
        Key = 'SubType_Label_Others',
        zh_CN = '其他',
        en = 'Others',
        id = 'Lainnya'
    },
    SubType_Label_MiniDresses = {
        Key = 'SubType_Label_MiniDresses',
        zh_CN = '迷你连衣裙',
        en = 'Mini Dresses',
        id = 'Gaun Mini'
    },
    SubType_Label_LongDresses = {
        Key = 'SubType_Label_LongDresses',
        zh_CN = '长款连衣裙',
        en = 'Long Dresses',
        id = 'Gaun Panjang'
    },
    SubType_Label_Sets = {
        Key = 'SubType_Label_Sets',
        zh_CN = '套装',
        en = 'Sets',
        id = 'Set'
    },
    SubType_Label_Tshirts = {
        Key = 'SubType_Label_Tshirts',
        zh_CN = 'T恤',
        en = 'T-shirts',
        id = 'Kaus'
    },
    SubType_Label_Shirts = {
        Key = 'SubType_Label_Shirts',
        zh_CN = '衬衫',
        en = 'Shirts',
        id = 'Kemeja'
    },
    SubType_Label_Sweaters = {
        Key = 'SubType_Label_Sweaters',
        zh_CN = '卫衣',
        en = 'Sweaters',
        id = 'Sweter'
    },
    SubType_Label_CropTops = {
        Key = 'SubType_Label_CropTops',
        zh_CN = '露脐装',
        en = 'Crop Tops',
        id = 'Crop Top'
    },
    SubType_Label_ShortJackets = {
        Key = 'SubType_Label_ShortJackets',
        zh_CN = '短外套',
        en = 'Short Jackets',
        id = 'Jaket Pendek'
    },
    SubType_Label_Jackets = {
        Key = 'SubType_Label_Jackets',
        zh_CN = '中长外套',
        en = 'Jackets',
        id = 'Jaket'
    },
    SubType_Label_Coats = {
        Key = 'SubType_Label_Coats',
        zh_CN = '长外套',
        en = 'Coats',
        id = 'Mantel'
    },
    SubType_Label_Shorts = {
        Key = 'SubType_Label_Shorts',
        zh_CN = '短裤',
        en = 'Shorts',
        id = 'Celana Pendek'
    },
    SubType_Label_LongShorts = {
        Key = 'SubType_Label_LongShorts',
        zh_CN = '中长裤',
        en = 'Long Shorts',
        id = 'Celana Tiga Perempat'
    },
    SubType_Label_Pants = {
        Key = 'SubType_Label_Pants',
        zh_CN = '长裤',
        en = 'Pants',
        id = 'Celana'
    },
    SubType_Label_Skirts = {
        Key = 'SubType_Label_Skirts',
        zh_CN = '短裙',
        en = 'Skirts',
        id = 'Rok'
    },
    SubType_Label_MidSkirts = {
        Key = 'SubType_Label_MidSkirts',
        zh_CN = '中长裙',
        en = 'Mid Skirts',
        id = 'Rok Panjang'
    },
    SubType_Label_Dresses = {
        Key = 'SubType_Label_Dresses',
        zh_CN = '长裙',
        en = 'Dresses',
        id = 'Gaun'
    },
    SubType_Label_Anklets = {
        Key = 'SubType_Label_Anklets',
        zh_CN = '船袜',
        en = 'Anklets',
        id = 'Gelang Kaki'
    },
    SubType_Label_Socks = {
        Key = 'SubType_Label_Socks',
        zh_CN = '短袜',
        en = 'Socks',
        id = 'Kaus Kaki'
    },
    SubType_Label_LongSocks = {
        Key = 'SubType_Label_LongSocks',
        zh_CN = '小腿袜',
        en = 'Long Socks',
        id = 'Kaus Kaki Panjang'
    },
    SubType_Label_Leggings = {
        Key = 'SubType_Label_Leggings',
        zh_CN = '大腿袜',
        en = 'Leggings',
        id = 'Legging'
    },
    SubType_Label_Pantyhoses = {
        Key = 'SubType_Label_Pantyhoses',
        zh_CN = '连裤袜',
        en = 'Pantyhoses',
        id = 'Stoking'
    },
    SubType_Label_LeatherShoes = {
        Key = 'SubType_Label_LeatherShoes',
        zh_CN = '皮鞋',
        en = 'Leather Shoes',
        id = 'Sepatu Kulit'
    },
    SubType_Label_Sneakers = {
        Key = 'SubType_Label_Sneakers',
        zh_CN = '运动鞋',
        en = 'Sneakers',
        id = 'Sneaker'
    },
    SubType_Label_Slippers = {
        Key = 'SubType_Label_Slippers',
        zh_CN = '拖鞋',
        en = 'Slippers',
        id = 'Selop'
    },
    SubType_Label_Boots = {
        Key = 'SubType_Label_Boots',
        zh_CN = '靴子',
        en = 'Boots',
        id = 'Sepatu Bot'
    },
    SubType_Label_Bracelets = {
        Key = 'SubType_Label_Bracelets',
        zh_CN = '手链',
        en = 'Bracelets',
        id = 'Gelang'
    },
    SubType_Label_Necklaces = {
        Key = 'SubType_Label_Necklaces',
        zh_CN = '项链',
        en = 'Necklaces',
        id = 'Kalung'
    },
    SubType_Label_Earrings = {
        Key = 'SubType_Label_Earrings',
        zh_CN = '耳环',
        en = 'Earrings',
        id = 'Anting'
    },
    SubType_Label_Bags = {
        Key = 'SubType_Label_Bags',
        zh_CN = '包',
        en = 'Bags',
        id = 'Tas'
    },
    SubType_Label_Gloves = {
        Key = 'SubType_Label_Gloves',
        zh_CN = '手套',
        en = 'Gloves',
        id = 'Sarung Tangan'
    },
    SubType_Label_Face = {
        Key = 'SubType_Label_Face',
        zh_CN = '脸型',
        en = 'Face',
        id = 'Wajah'
    },
    SubType_Label_Body = {
        Key = 'SubType_Label_Body',
        zh_CN = '体型',
        en = 'Body',
        id = 'Bodi'
    },
    Category_Title_Outfit = {
        Key = 'Category_Title_Outfit',
        zh_CN = '服装',
        en = 'Outfit',
        id = 'Pakaian'
    },
    Category_Title_Physique = {
        Key = 'Category_Title_Physique',
        zh_CN = '体型',
        en = 'Physique',
        id = 'Fisik'
    },
    Global_Text_Source = {
        Key = 'Global_Text_Source',
        zh_CN = '获取途径',
        en = 'Source',
        id = 'Sumber'
    },
    Global_Text_Day = {
        Key = 'Global_Text_Day',
        zh_CN = '天',
        en = 'd',
        id = 'h'
    },
    Global_Text_Hour = {
        Key = 'Global_Text_Hour',
        zh_CN = '小时',
        en = 'h',
        id = 'j'
    },
    Global_Text_Minute = {
        Key = 'Global_Text_Minute',
        zh_CN = '分钟',
        en = 'm',
        id = 'm'
    },
    Global_Text_Second = {
        Key = 'Global_Text_Second',
        zh_CN = '秒',
        en = 's',
        id = 'd'
    },
    Global_Text_Expired = {
        Key = 'Global_Text_Expired',
        zh_CN = '已到期',
        en = 'Expired',
        id = 'Kedaluwarsa'
    }
}

return I18NXls
