--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./xls/Gui.xlsx

local MainTypeXls = {
    [1] = {
        SN = 1,
        MainType = '01',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Hair',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_hair1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_hair'
    },
    [2] = {
        SN = 2,
        MainType = '02',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Head',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_head1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_head'
    },
    [3] = {
        SN = 3,
        MainType = '03',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Mask',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_mask1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_mask'
    },
    [4] = {
        SN = 4,
        MainType = '04',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Suit',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_suit1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_suit'
    },
    [5] = {
        SN = 5,
        MainType = '05',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Clothes',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_clothes1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_clothes'
    },
    [6] = {
        SN = 6,
        MainType = '06',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Coat',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_coat1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_coat'
    },
    [7] = {
        SN = 7,
        MainType = '07',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Pants',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_pants1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_pants'
    },
    [8] = {
        SN = 8,
        MainType = '08',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Dress',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_dress1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_dress'
    },
    [9] = {
        SN = 9,
        MainType = '09',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Socks',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_sock1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_sock'
    },
    [10] = {
        SN = 10,
        MainType = '10',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Shoes',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_shoes1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_shoes'
    },
    [11] = {
        SN = 11,
        MainType = '11',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Jewellery',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_jewellery1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_jewellery'
    },
    [12] = {
        SN = 12,
        MainType = '12',
        Category = 'Outfit',
        Enable = true,
        NodeName = 'Accessory',
        ResIcon = 'Outfit/Gui/Icon/svg_Sic_bag1',
        ResIconPressed = 'Outfit/Gui/Icon/svg_Sic_bag'
    }
}

return MainTypeXls
