--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./xls/Gui.xlsx

local SubTypeXls = {
    [1] = {
        SN = 1,
        SubType = {'0101', '0102', '0103', '0104', '0105'},
        MainType = '01',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [2] = {
        SN = 2,
        SubType = {'0101'},
        MainType = '01',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Short'
    },
    [3] = {
        SN = 3,
        SubType = {'0102'},
        MainType = '01',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Medium'
    },
    [4] = {
        SN = 4,
        SubType = {'0103'},
        MainType = '01',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Long'
    },
    [5] = {
        SN = 5,
        SubType = {'0104'},
        MainType = '01',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Braids'
    },
    [6] = {
        SN = 6,
        SubType = {'0105'},
        MainType = '01',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Special'
    },
    [7] = {
        SN = 7,
        SubType = {'0201', '0202', '0203'},
        MainType = '02',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [8] = {
        SN = 8,
        SubType = {'0201'},
        MainType = '02',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Accessories'
    },
    [9] = {
        SN = 9,
        SubType = {'0202'},
        MainType = '02',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Hats'
    },
    [10] = {
        SN = 10,
        SubType = {'0203'},
        MainType = '02',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Fun'
    },
    [11] = {
        SN = 11,
        SubType = {'0301', '0302', '0303'},
        MainType = '03',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [12] = {
        SN = 12,
        SubType = {'0301'},
        MainType = '03',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Glasses'
    },
    [13] = {
        SN = 13,
        SubType = {'0302', '0302'},
        MainType = '03',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Others'
    },
    [14] = {
        SN = 14,
        SubType = {'0401', '0402', '0403', '0404'},
        MainType = '04',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [15] = {
        SN = 15,
        SubType = {'0401'},
        MainType = '04',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_MiniDresses'
    },
    [16] = {
        SN = 16,
        SubType = {'0402'},
        MainType = '04',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_LongDresses'
    },
    [17] = {
        SN = 17,
        SubType = {'0403'},
        MainType = '04',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Sets'
    },
    [18] = {
        SN = 18,
        SubType = {'0404'},
        MainType = '04',
        Category = 'Outfit',
        Enable = false,
        CheckNew = true,
        _Label = 'SubType_Label_Fun'
    },
    [19] = {
        SN = 19,
        SubType = {'0501', '0502', '0503', '0504'},
        MainType = '05',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [20] = {
        SN = 20,
        SubType = {'0501'},
        MainType = '05',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Tshirts'
    },
    [21] = {
        SN = 21,
        SubType = {'0502'},
        MainType = '05',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Shirts'
    },
    [22] = {
        SN = 22,
        SubType = {'0503'},
        MainType = '05',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Sweaters'
    },
    [23] = {
        SN = 23,
        SubType = {'0504'},
        MainType = '05',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_CropTops'
    },
    [24] = {
        SN = 24,
        SubType = {'0601', '0602', '0603'},
        MainType = '06',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [25] = {
        SN = 25,
        SubType = {'0601'},
        MainType = '06',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_ShortJackets'
    },
    [26] = {
        SN = 26,
        SubType = {'0602'},
        MainType = '06',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Jackets'
    },
    [27] = {
        SN = 27,
        SubType = {'0603'},
        MainType = '06',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Coats'
    },
    [28] = {
        SN = 28,
        SubType = {'0701', '0702', '0703'},
        MainType = '07',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [29] = {
        SN = 29,
        SubType = {'0701'},
        MainType = '07',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Shorts'
    },
    [30] = {
        SN = 30,
        SubType = {'0702'},
        MainType = '07',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_LongShorts'
    },
    [31] = {
        SN = 31,
        SubType = {'0703'},
        MainType = '07',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Pants'
    },
    [32] = {
        SN = 32,
        SubType = {'0801', '0802', '0803'},
        MainType = '08',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [33] = {
        SN = 33,
        SubType = {'0801'},
        MainType = '08',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Skirts'
    },
    [34] = {
        SN = 34,
        SubType = {'0802'},
        MainType = '08',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_MidSkirts'
    },
    [35] = {
        SN = 35,
        SubType = {'0803'},
        MainType = '08',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Dresses'
    },
    [36] = {
        SN = 36,
        SubType = {'0901', '0902', '0903', '0904', '0905'},
        MainType = '09',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [37] = {
        SN = 37,
        SubType = {'0901'},
        MainType = '09',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Anklets'
    },
    [38] = {
        SN = 38,
        SubType = {'0902'},
        MainType = '09',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Socks'
    },
    [39] = {
        SN = 39,
        SubType = {'0903'},
        MainType = '09',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_LongSocks'
    },
    [40] = {
        SN = 40,
        SubType = {'0904'},
        MainType = '09',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Leggings'
    },
    [41] = {
        SN = 41,
        SubType = {'0905'},
        MainType = '09',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Pantyhoses'
    },
    [42] = {
        SN = 42,
        SubType = {'1001', '1002', '1003', '1004'},
        MainType = '10',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [43] = {
        SN = 43,
        SubType = {'1001'},
        MainType = '10',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_LeatherShoes'
    },
    [44] = {
        SN = 44,
        SubType = {'1002'},
        MainType = '10',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Sneakers'
    },
    [45] = {
        SN = 45,
        SubType = {'1003'},
        MainType = '10',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Slippers'
    },
    [46] = {
        SN = 46,
        SubType = {'1004'},
        MainType = '10',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Boots'
    },
    [47] = {
        SN = 47,
        SubType = {'1101', '1102', '1103'},
        MainType = '11',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [48] = {
        SN = 48,
        SubType = {'1101'},
        MainType = '11',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Bracelets'
    },
    [49] = {
        SN = 49,
        SubType = {'1102'},
        MainType = '11',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Necklaces'
    },
    [50] = {
        SN = 50,
        SubType = {'1103'},
        MainType = '11',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Earrings'
    },
    [51] = {
        SN = 51,
        SubType = {'1201', '1202', '1301', '1302'},
        MainType = '12',
        Category = 'Outfit',
        Enable = true,
        CheckNew = false,
        _Label = 'SubType_Label_All'
    },
    [52] = {
        SN = 52,
        SubType = {'1201'},
        MainType = '12',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Bags'
    },
    [53] = {
        SN = 53,
        SubType = {'1202'},
        MainType = '12',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Gloves'
    },
    [54] = {
        SN = 54,
        SubType = {'1301', '1302'},
        MainType = '12',
        Category = 'Outfit',
        Enable = true,
        CheckNew = true,
        _Label = 'SubType_Label_Others'
    }
}

return SubTypeXls
