--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/UiInfoTable.xlsx

local BtnBaseTableXls = {
    BtnClose = {
        Name = 'BtnClose',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0.87, 1),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  25,  255),
        Texture = 'MenuRes/Btn_Idle',
        Id = 0
    },
    BtnGaming = {
        Name = 'BtnGaming',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0.74, 0.87),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  25,  255),
        Texture = 'MenuRes/Btn_Selected',
        Id = 1
    },
    BtnSetting = {
        Name = 'BtnSetting',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0.61, 0.74),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  25,  255),
        Texture = 'MenuRes/Btn_Idle',
        Id = 2
    },
    BtnDressUp = {
        Name = 'BtnDressUp',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0.48, 0.61),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  25,  255),
        Texture = 'MenuRes/Btn_Idle',
        Id = 3
    },
    BtnQuit = {
        Name = 'BtnQuit',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 0.13),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  25,  255),
        Texture = 'MenuRes/Btn_Idle',
        Id = -1
    }
}

return BtnBaseTableXls
