--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/UiInfoTable.xlsx

local BtnBaseTableXls = {
    BtnClose = {
        Name = 'BtnClose',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.1, 1),
        AnchorsY = Vector2(0.9, 1),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  0),
        Texture = 'MenuRes/Icon_Idle'
    },
    BtnGame = {
        Name = 'BtnGame',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.1, 1),
        AnchorsY = Vector2(0.8, 0.9),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Icon_Selected'
    },
    BtnSetting = {
        Name = 'BtnSetting',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.1, 1),
        AnchorsY = Vector2(0.67, 0.77),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Icon_Idle'
    },
    BtnClot = {
        Name = 'BtnClot',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.1, 1),
        AnchorsY = Vector2(0.54, 0.64),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Icon_Idle'
    },
    BtnShot = {
        Name = 'BtnShot',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.1, 1),
        AnchorsY = Vector2(0.41, 0.51),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Icon_Idle'
    },
    BtnQuit = {
        Name = 'BtnQuit',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.1, 1),
        AnchorsY = Vector2(0, 0.1),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Icon_IdleQ'
    }
}

return BtnBaseTableXls
