--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/UiInfoTable.xlsx

local BtnOutTableXls = {
    BtnMenu = {
        Name = 'BtnMenu',
        Size = Vector2(54, 54),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.04, 0.04),
        AnchorsY = Vector2(0.95, 0.95),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Btn_Menu'
    },
    BtnVoice = {
        Name = 'BtnVoice',
        Size = Vector2(54, 54),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.09, 0.09),
        AnchorsY = Vector2(0.95, 0.95),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Btn_Voice'
    }
}

return BtnOutTableXls
