--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/UiInfoTable.xlsx

local DisplayBaseTableXls = {
    ImgGaming = {
        Name = 'ImgGaming',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 1),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255, 255, 0),
        Texture = '',
        Id = 1
    },
    ImgSetting = {
        Name = 'ImgSetting',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 1),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255, 255, 0),
        Texture = '',
        Id = 2
    },
    ImgDressUp = {
        Name = 'ImgDressUp',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 1),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255, 255, 0),
        Texture = '',
        Id = 3
    }
}

return DisplayBaseTableXls
