--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/UiInfoTable.xlsx

local FontTypeTableXls = {
    TextSetting = {
        Name = 'TextSetting',
        FrontSize = 50,
        Text = 'Setting',
        Color = Color(255,  255,  255,  255)
    },
    TextAutoSet = {
        Name = 'TextAutoSet',
        FrontSize = 50,
        Text = 'Auto-Set',
        Color = Color(255,  255,  255,  255)
    },
    TextGraphicSetting = {
        Name = 'TextGraphicSetting',
        FrontSize = 50,
        Text = 'GraphicSetting',
        Color = Color(255,  255,  255,  255)
    },
    TextShut = {
        Name = 'TextShut',
        FrontSize = 50,
        Text = '',
        Color = Color(255,  255,  255,  255)
    },
    TextOpen = {
        Name = 'TextOpen',
        FrontSize = 50,
        Text = '',
        Color = Color(255,  255,  255,  255)
    },
    TextLow = {
        Name = 'TextLow',
        FrontSize = 50,
        Text = '',
        Color = Color(255,  255,  255,  255)
    },
    TextMedium = {
        Name = 'TextMedium',
        FrontSize = 50,
        Text = '',
        Color = Color(255,  255,  255,  255)
    },
    TextHigh = {
        Name = 'TextHigh',
        FrontSize = 50,
        Text = '',
        Color = Color(255,  255,  255,  255)
    }
}

return FontTypeTableXls
