--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/UiInfoTable.xlsx

local RootTableXls = {
    ImgBase = {
        Name = 'ImgBase',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.1, 0.5),
        AnchorsY = Vector2(0.02, 0.98),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Icon_Base'
    },
    BtnBase = {
        Name = 'BtnBase',
        Size = Vector2(0, 0),
        Pivot = Vector2(0, 0),
        AnchorsX = Vector2(0, 0.1),
        AnchorsY = Vector2(0.02, 0.98),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  0),
        Texture = ''
    }
}

return RootTableXls
