--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/UiInfoTable.xlsx

local SettingTableXls = {
    TextSetting = {
        Name = 'TextSetting',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.15, 0.25),
        AnchorsY = Vector2(0.87, 1),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = '',
        ClassName = 'UiTextObject',
        ParentName = 'ImgSetting'
    },
    TextAutoSet = {
        Name = 'TextAutoSet',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.15, 0.25),
        AnchorsY = Vector2(0.74, 0.87),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = '',
        ClassName = 'UiTextObject',
        ParentName = 'ImgSetting'
    },
    TextGraphicSetting = {
        Name = 'TextGraphicSetting',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0.15, 0.25),
        AnchorsY = Vector2(0.61, 0.74),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = '',
        ClassName = 'UiTextObject',
        ParentName = 'ImgSetting'
    },
    ImgAutoSet = {
        Name = 'ImgAutoSet',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 0.17),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Img_AutoSet',
        ClassName = 'UiImageObject',
        ParentName = 'ImgSetting'
    },
    ImgGraphicSetting = {
        Name = 'ImgGraphicSetting',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 0.19),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Img_GraphicSetting',
        ClassName = 'UiImageObject',
        ParentName = 'ImgSetting'
    },
    TextShut = {
        Name = 'TextShut',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0.48, 0.61),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = '',
        ClassName = 'UiTextObject',
        ParentName = 'ImgAutoSet'
    },
    TextOpen = {
        Name = 'TextOpen',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 0.13),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = '',
        ClassName = 'UiTextObject',
        ParentName = 'ImgAutoSet'
    },
    BtnAutoSet = {
        Name = 'BtnAutoSet',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 0.18),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Btn_AutoSet',
        ClassName = 'UiButtonObject',
        ParentName = 'ImgAutoSet'
    },
    TextLow = {
        Name = 'TextLow',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 0.14),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = '',
        ClassName = 'UiTextObject',
        ParentName = 'ImgGraphicSetting'
    },
    TextMedium = {
        Name = 'TextMedium',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 0.15),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = '',
        ClassName = 'UiTextObject',
        ParentName = 'ImgGraphicSetting'
    },
    TextHigh = {
        Name = 'TextHigh',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 0.16),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = '',
        ClassName = 'UiTextObject',
        ParentName = 'ImgGraphicSetting'
    },
    BtnGraphicSetting = {
        Name = 'BtnGraphicSetting',
        Size = Vector2(0, 0),
        Pivot = Vector2(0.5, 0.5),
        AnchorsX = Vector2(0, 1),
        AnchorsY = Vector2(0, 0.20),
        Angle = 0.0,
        Offset = Vector2(0, 0),
        Color = Color(255,  255,  255,  255),
        Texture = 'MenuRes/Btn_GraphicSetting',
        ClassName = 'UiButtonObject',
        ParentName = 'ImgGraphicSetting'
    }
}

return SettingTableXls
